# -*- coding: utf-8 -*-
"""assignment1_(mod2).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZySCe2Ek9oPhldDeYTPNkWrqUQ0Hgqxr

Assignment 1 _ (mod 2)
Assignment: 01

Understanding Data Structures and Functions

Problem: 01

Write a function that takes two numbers as input and returns their average. Call the function with different values.
"""

# Function to calculate average of two numbers
def find_average(num1, num2):
    return (num1 + num2) / 2

# Calling the function with different values
print("Average of 10 and 20 is:", find_average(10, 20))
print("Average of 5 and 15 is:", find_average(5, 15))
print("Average of 7.5 and 2.5 is:", find_average(7.5, 2.5))
print("Average of -10 and 30 is:", find_average(-10, 30))

"""Problem: 02

Write a function that sorts a list of strings alphabetically.

["apple", "banana", "cherry", "kiwi", "grape"]
"""

# Function to sort a list of strings alphabetically
def sort_strings(words):
    return sorted(words)

# Given list
fruits = ["apple", "banana", "cherry", "kiwi", "grape"]

# Calling the function
sorted_fruits = sort_strings(fruits)
print("Sorted list:", sorted_fruits)

"""Problem: 03

Write a Python program that creates a new list containing only the duplicate elements from the given list: [1, 5, 6, 5, 1, 2, 3].
"""

# Given list
numbers = [1, 5, 6, 5, 1, 2, 3]

# Find duplicates
duplicates = []
for num in numbers:
    if numbers.count(num) > 1 and num not in duplicates:
        duplicates.append(num)

print("Duplicate elements:", duplicates)