# -*- coding: utf-8 -*-
"""Assignment 2 _ (mod 2).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hJbZfq5tBZzAlvza1TBRkeSddhK_yYKc

Assignment 2 _ (mod 2)
Advanced-Data Structures and Comparison
Write a Python program that takes two sets from the user and computes their union, intersection, and difference.

A = {1, 2, 3, 4, 5}

B = {4, 5, 6, 7, 8}
"""

# Taking input from the user
A = set(map(int, input("Enter elements for set A (separated by space): ").split()))
B = set(map(int, input("Enter elements for set B (separated by space): ").split()))

# Compute the union, intersection, and difference
union = A.union(B)
intersection = A.intersection(B)
difference_A_B = A.difference(B)
difference_B_A = B.difference(A)

# Output the results
print("Union of A and B:", union)
print("Intersection of A and B:", intersection)
print("Difference of A - B:", difference_A_B)
print("Difference of B - A:", difference_B_A)